### ISSUE TITLE
Posting a new entityDefs does not work

### ISSUE THREAD

**Issue by Nyna71** [jpoullet2000/atlasclient#22]
When posting a new entity type definition (see example below), AtlasClient returns a 200 OK, with "All typedefs already exist!"

The entityDefs is however not created. Posting the below JSON directly in the Atlas API results in the entityDef being created.

Posting a new enumDef or classificationDef however works fine.

example:
{
    "entityDefs": [
        {
		    "category": "ENTITY",
		    "name": "test_entityDefs",
		    "description": "test_entityDefs",
		    "attributeDefs": [
		        {
		            "name": "test_attribute",
		            "typeName": "file_action",
		            "isOptional": false,
		            "cardinality": "SINGLE",
		            "valuesMinCount": 1,
		            "valuesMaxCount": 1,
		            "isUnique": false,
		            "isIndexable": false
		        }
		    ],
		    "superTypes": [
		        "DataSet"
		    ]
        }
    ]
}

**Comment by jpoullet2000** [comment]
This is not a message from **atlasclient** but **det** (see [here](https://github.com/jpoullet2000/det/search?q=All+typedefs+already+exist%21&unscoped_q=All+typedefs+already+exist%21) ). **det** is checking the existing atlas entities before sending a post request. In your case, it seems that the entity already existed, resulting in the message _200 OK, with "All typedefs already exist!_". I'm closing the comment since this seems to be related to **det** and not **atlasclient**.

**Comment by Nyna71** [comment]
Indeed, I validated the Atlas client client.typedefs.create(data=typedef_dict) and it posted the typeDefs correctly. The issue reside on the **det** client, which cannot post a new typeDefs of type entity. I'll debug and correct it.
